name: Linting, testing and builbing
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps: 
          - uses: actions/checkout@v2
          - name: Starting NodeJS ${{ matrix.node-version }}
          uses: action/setup-node@1
          with: 
              node-version: ${{ matrix.node-version }}
          - name: install modules
          run: npm install
          - name: build production project
          run: npm run build:prod
          - name: linting ts
          run: npm run lint:ts
          - name: build css
          run: npm run lint:scss
          - name: unit testing
          run: npm run test:unit
          - name: ui testing
          run: npm run test:ui
          - name: build storybook
          run: npm run build-storybook